server:
  port: 443
  address: 0.0.0.0

lavalink:
  server:
    password: "69"
    playerUpdateInterval: 5
    statsTaskInterval: 60
    koe:
      useEpoll: true
      highPacketPriority: true
      bufferDurationMs: 400
      byteBufAllocator: "default"
    sources:
      bandcamp: true
      getyarn: true
      http: true
      odysee: true
      reddit: true
      soundcloud: true
      spotify : true
      tiktok: true
      twitch: true
      vimeo: true
      yandex: true
      youtube: true
      local: false
    lavaplayer:
      nonAllocating: false
      frameBufferDuration: 5000
      youtubePlaylistLoadLimit: 6
      gc-warnings: true
      youtubeSearchEnabled: true
      odyseeSearchEnabled: true
      soundcloudSearchEnabled: true
      yandexMusicSearchEnabled: true
      ratelimit:
        retryLimit: 5
      #youtubeConfig:
        #email: ""
        #password: ""

metrics:
  prometheus:
    enabled: true
    endpoint: /metrics

sentry:
  dsn: ""
  environment: ""
  level:
    root: INFO
    lavalink: INFO
